name: Build and push image

on:
  push:
    tags: ["*"]

env:
  IMAGE_NAME: hegemone-server
  IMAGE_TAGS: ${{ github.ref_name }}
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAMESPACE: redpill-linpro

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Build with Maven
        run: mvn verify

      - name: Build arm64 image
        id: build-arm64-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}-arm64
          archs: arm64
          containerfiles: |
            ./Containerfile.arm64

      - name: Push arm64 image to registry
        id: push-arm64-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-arm64-image.outputs.image }}
          tags: ${{ steps.build-arm64-image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAMESPACE }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-arm64-to-registry.outputs.registry-paths }}"
      
      - name: Build amd64 image
        id: build-amd64-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}-amd64
          archs: amd64
          containerfiles: |
            ./Containerfile.amd64

      - name: Push amd64 image to registry
        id: push-amd64-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-amd64-image.outputs.image }}
          tags: ${{ steps.build-amd64-image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAMESPACE }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-amd64-to-registry.outputs.registry-paths }}"