name: Create and publish a Docker image

on:
  push:
    tags: ["*"]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Build with Maven
        run: mvn verify

      - name: Build arm64 image
        id: build-arm64-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ github.repository }}
          tags: ${{ github.ref }}
          archs: arm64
          containerfiles: |
            ./Containerfile.arm64

      - name: Push to ghcr.io
        id: push-arm64-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-arm64-image.outputs.image }}
          tags: ${{ steps.build-arm64-image.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-arm64-to-ghcr.outputs.registry-paths }}"

      - name: Build amd64 image
        id: build-amd64-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ github.repository }}
          tags: ${{ github.ref }}
          archs: amd64
          containerfiles: |
            ./Containerfile.amd64

      - name: Push to ghcr.io
        id: push-amd64-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-amd64-image.outputs.image }}
          tags: ${{ steps.build-amd64-image.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-amd64-to-ghcr.outputs.registry-paths }}"